pipeline {

    agent {
        node {
            label 'Jenkins_agent'
        } 
    }
    // environment {
    //     // using the environment variables here
    //     PackageVersion = ''
    //     nexusURL = '172.31.32.58:8081/repository'
    // }

    options {
        timeout(time: 1 , unit: "HOURS")
        disableConcurrentBuilds()
    }
    parameters {
        string(name: 'version' , defaultValue: '' , description: 'what is artifact version')
        string(name: 'environment' , defaultValue: '' , description: 'what is the environment')
    }
    stages {
        stage("Getting the version of the file") {
            steps {
                sh """
                    echo "version: ${params.version}" 
                    echo "environment: ${params.environment}"  

                """
            }
        }
        stage('installing dependencies') {
            steps {
                // Add npm steps here
                sh """
                    echo installing npm dependencies 
                    pwd
                    npm install
                    """ 
            }
        }
        stage('Building Application') {
            steps {
                // Add npm steps here
                sh """
                    ls -la
                    zip -q -r catalogue.zip ./* -x jenkinsfile -x ".git" -x "*Jenkinsfile" -x "*.zip"
                    ls -a
                    """ 
            }
        }
        stage('punshing the arifactory into nexus') {
            steps {
                    nexusArtifactUploader(
                        nexusVersion: 'nexus3',
                        protocol: 'http',
                        nexusUrl: "${nexusURL}",
                        groupId: 'com.roboshop',
                        version: "${PackageVersion}",
                        repository: 'catalogue',
                        credentialsId: 'nexus-cred',
                        artifacts: [
                            [artifactId: 'catalogue',
                            classifier: '',
                            file: 'catalogue.zip',
                            type: 'zip']
                        ]
                    )
            }
        }
        stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps {
                // Add deploy steps here
                sh 'echo "Deploying..."'
            }
        }
        stage('release') {
            steps {
                // Add release steps here
                sh 'echo "releasing the application..."'
            }
        }
        
    }
    post {
        always {
            echo "pipeline is running...."
            deleteDir()
        }
        failure {
            echo "pipeline is failure..."
        }
        success {
            echo "pipeline is success...party..ledha..pushpa.."
        }
    }
} 